#--------------- Configuration Docker ----------------------#

# Spring configuration
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuerUri: http://${KEYCLOAK_FRONT_HOST}:8080/realms/digitalMoneyHouse
          jwkSetUri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/certs
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: accounts

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka