#--------------- Configuration Docker ----------------------#

# Spring configuration
spring:
  application:
    name: ms-transactions
  security:
    oauth2:
      client:
        provider:
          keycloak:
            tokenUri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/token
      resource-server:
        jwt:
          issuerUri: http://${KEYCLOAK_FRONT_HOST}:8080/realms/digitalMoneyHouse
          jwkSetUri: http://${KEYCLOAK_HOST}:8080/realms/digitalMoneyHouse/protocol/openid-connect/certs
  data:
    mongodb:
      uri: mongodb://mongodb:27017
      database: transactions

  # Kafka configuration
  kafka:
    bootstrap-servers: broker:9092

# Eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

# Feign configuration
feign:
  cards:
    url: http://cards:8092
  accounts:
    url: http://accounts:8091